# ------------------------------------------------------------------------------
# Symbolic Constants for Variable Names
# ------------------------------------------------------------------------------

#
# Key: a string representing the key for a data group
#
GROUP = group