# ------------------------------------------------------------------------------
# Header Constants
# ------------------------------------------------------------------------------
#
AUTHORIZATION = "Authorization"
CONTENT_TYPE = "Content-Type"
LOCATION = "Location"