# ------------------------------------------------------------------------------
# OASE H2 Messages
# ------------------------------------------------------------------------------
#
CONSOLE_DISABLED = H2 Web Console is disabled.
CONSOLE_STOPPED = H2 Web Console stopped. 