autoCommit = false
connectionTimeoutMs = 3000
driverClass = org.h2.Driver
jdbcUrl = "jdbc:h2:./H2/WMH;DB_CLOSE_DELAY=-1"
maxPoolSize = 10
minIdle = 4
password = ""
schema = PUBLIC
username = sa