# ------------------------------------------------------------------------------
# OASE JDBC Messages
# ------------------------------------------------------------------------------
#
CONNECTION_NOT_CLOSED = Connection to database '{}' could not be closed.
DSFACTORY_NOT_FOUND = DataSourceFactory not found for driver class '{}'.
SQL_STATEMENT_EMPTY = SQL statement is empty.