# ------------------------------------------------------------------------------
# OASE JDBC Messages
# ------------------------------------------------------------------------------
#
DSFACTORY_NOT_FOUND = DataSourceFactory not found for driver class '{}'.
SQL_FILE_EMPTY = SQL file '{}' is empty.